version = 1
disable_existing_loggers = false

[formatters.simple]
format = "%(levelname)s: %(message)s"
datefmt = "%Y-%m-%d %H:%M:%S"

[formatters.detailed]
format = "%(asctime)s - %(name)s - %(levelname)s - %(pathname)s:%(lineno)d - %(message)s"
datefmt = "%Y-%m-%d %H:%M:%S"

[handlers.console]
class = "logging.StreamHandler"
level = "DEBUG"
formatter = "simple"
stream = "ext://sys.stdout"

[handlers.dev_file]
class = "logging.handlers.RotatingFileHandler"
level = "DEBUG"
formatter = "detailed"
filename = "logs/dev.log"
maxBytes = 10485760  # 10MB
backupCount = 5
encoding = "utf-8"

[handlers.prod_file]
class = "logging.handlers.TimedRotatingFileHandler"
level = "INFO"
formatter = "detailed"
filename = "logs/prod.log"
when = "midnight"
interval = 1
backupCount = 7
encoding = "utf-8"

[loggers."myapp.dev"]
level = "DEBUG"
handlers = ["console", "dev_file"]
propagate = false

[loggers."myapp.prod"]
level = "INFO"
handlers = ["console", "prod_file"]
propagate = false

[root]
level = "WARNING"
handlers = ["console"]